### ISSUE TITLE
denoising 1D data

### ISSUE THREAD

**Issue by psteinb** [juglab/n2v#105]
Hi,

after we made good experiences with N2V and friends, we are wondering how the same tooling works on 1D data, aka time series. Are there any code snippets around, that could help us give N2V a try on such data?

Best

**Comment by tibuch** [comment]
Hi @psteinb,

Unfortunately we don't have 1D code snippets :/ I know that someone once tried to use N2V for 1D data and they ended up embedding their data in a 2D image (zeros) and then used 2D N2V. Maybe this could work for you as well.

Or you try to replace all 2D operations with 1D operations. But I am not sure how much work this requires.

Best

**Comment by psteinb** [comment]
Thanks for letting us know. As this is not super urgent on my end, i close the issue in good hope that you or @fjug or @alex-krull are aware of this from here on. 

If there are developments with respect to N2V on 1D on your end, please let me know. Just in case, we find resources on our end, will do the same.

Best
