### ISSUE TITLE
Issue with creating the network model from StructN2V

### ISSUE THREAD

**Issue by NikithaSiddappaRamesh** [juglab/n2v#106]
Hello,

I am trying to use the StructN2V model as part of my thesis work. But, when I execute the notebook associated with it (examples/2D/structN2V_2d_convallaria.ipynb), I am facing an issue when creating the network model using the code:

`model = N2V(config, model_name, basedir=basedir)`

The error is as follows:
AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'

I tried to implement few solution but had no luck with it. Any help with this will be very much appreciated, Thank You.

**Comment by tibuch** [comment]
Hi @NikithaSiddappaRamesh,

I just tried out the example in a freshly setup conda-env and hat no trouble running the structN2V example. Do other N2V examples work for you? 

I am using TensorFlow GPU 1.15, could it be that you are using TensorFlow 2? Unfortunately we didn't have the time yet to upgrade everything to TF2.

**Comment by NikithaSiddappaRamesh** [comment]
Hello @tibuch,

Thank You for the response. I checked and yes I am using TensorFlow version 2.4, I will downgrade it and see if it works. Thank you for your solution.
