### ISSUE TITLE
Examples fails due to auth login data

### ISSUE THREAD

**Issue by ctr26** [juglab/n2v#115]
Hi,

The data the example notebooks use is stored on mpi cloud which requires a login. Maybe point it to zenodo or biostudies?

Thanks

Craig

**Comment by fjug** [comment]
Urgs… moving away from Dresden we did actually update to other ways of hosting (Zenodo in many cases). Seems we missed it here… 😞 

@tibuch @alex-krull Who of your old MPI accounts host this data? Where would you prefer to make it live in the future?!?

**Comment by tibuch** [comment]
Indeed we have moved the data but not updated the links yet.

However, I can't reproduce the login error. I tried this link from the SEM example: https://cloud.mpi-cbg.de/index.php/s/pXgfbobntrw06lC/download

Which link did not work for you? 

Anyway, we should update the links.

**Comment by ctr26** [comment]
I was using this link:

https://cloud.mpi-cbg.de/index.php/s/pbj89sV6n6SyM29/download

But it’s working today… 

Feel free to close this issue, I have no idea what happened yesterday.

Apologies,

Craig

**Comment by tibuch** [comment]
I updated the download links.
