### ISSUE TITLE
2D RGB data not accessible anymore: 502 Bad Gateway

### ISSUE THREAD

**Issue by chloeskt** [juglab/n2v#118]
Hello, 

I am currently trying to train a model for 2D RGB denoising, following the given [notebook](https://github.com/juglab/n2v/blob/master/examples/2D/denoising2D_RGB/01_training.ipynb). 
However I noticed that the training data proposed, namely https://download.fht.org/jug/n2v/RGB.zip, is not accessible anymore due to a 502 error. 
Would it be possible to fix the link (even if it is not necessary, one can train on another RGB images)? 

Thanks !

**Comment by tibuch** [comment]
@jdeschamps could you have a look please? :innocent:

**Comment by fjug** [comment]
Thanks for pointing this out. We will look into this ASAP...

**Comment by jdeschamps** [comment]
Should be fixed now!

**Comment by tibuch** [comment]
Thanks :)

**Comment by chloeskt** [comment]
Thank you very much !
