### ISSUE TITLE
error in predicting model

### ISSUE THREAD

**Issue by MHMoazezian** [juglab/n2v#135]
Hi 
I trained the model with a 2D array with 1 channel with shape (1600, 256,256,1) after generating patches. 
when I want to predict the trained model with another image with a shape of (256,256) I got this error : 
**tile_overlap value for n_depth=6, kern_size=3, pool_size=2 not available.**
In your example just use an image as an input to the model.predict without any process!!
Python 3.6.9
TensorFlow 2.4 
n2v 0.3.1

**Comment by veegalinova** [comment]
Hi, can you please specify which of the examples you were following?

**Comment by jdeschamps** [comment]
I will close this issue due to lack of answers. Please do not hesitate to open a new one if you encounter problems.
