### ISSUE TITLE
Multi-channel tiff  (YXC) file denoising problem

### ISSUE THREAD

**Issue by honghongfang** [juglab/n2v#136]
Hello, my original file is a two-photon microscope tiff file with four channels of shape (26,574,574) ZXY, imaged by different fluorescent signals. I convert my image first to 26 frames (574,574) 2D image, I use N2V for denoising and it works fine. When I try to combine my 4 channels together, that is, the shape is (574,574,4) YXC image for denoising, there is a problem, the denoising effect is far worse than a single channel, and the predicted result is even worse Fuzzy, especially the second and fourth channels. Do you know why this is? Do you have any suggestions, thank you very much！

**Comment by honghongfang** [comment]
> Hi,
> 
> Have you set `single_net_per_channel=True` in the configuration (it is the default)?
> 
> Your channel likely have different features (structures, wavelengths) and noise distribution. If you train a single network, it will collate the four channels, and N2V will not work well.
> 
> In general, we advise to train a single network per channel.

yes i set single_net_per_channel=True, but still did not work well. so does this N2V only work well for RGB  with same features (structures, wavelengths) and noise distribution?

**Comment by honghongfang** [comment]
> Hi,
> 
> Have you set `single_net_per_channel=True` in the configuration (it is the default)?
> 
> Your channel likely have different features (structures, wavelengths) and noise distribution. If you train a single network, it will collate the four channels, and N2V will not work well.
> 
> In general, we advise to train a single network per channel.

I've trained a single channel model to denoise images(574,574) from each of the 4 channels independently, and it worked fine. I don't know, it might be slightly worse than joint models（574,574,4） (single_net_per_channel=True) or same  - but it works fine at the first glance. and actually it is better than  joint models（574,574,4） (single_net_per_channel=True) , do you know why?

**Comment by jdeschamps** [comment]
> > Hi,
> > Have you set `single_net_per_channel=True` in the configuration (it is the default)?
> > Your channel likely have different features (structures, wavelengths) and noise distribution. If you train a single network, it will collate the four channels, and N2V will not work well.
> > In general, we advise to train a single network per channel.
> 
> yes i set single_net_per_channel=True, but still did not work well. so does this N2V only work well for RGB with same features (structures, wavelengths) and noise distribution?
> 
> I've trained a single channel model to denoise images(574,574) from each of the 4 channels independently, and it worked fine. I don't know, it might be slightly worse than joint models（574,574,4） (single_net_per_channel=True) or same - but it works fine at the first glance. and actually it is better than joint models（574,574,4） (single_net_per_channel=True) , do you know why?

Normally `single_net_per_channel=True` should give you about the same results than training a model for each channel. 

But what `single_net_per_channel=True` actually does is creating a model with a UNet branch per channel. Then there is a single loss for all channels. So the training is slightly different than training individual channels with one model each. Somehow, maybe because of normalization or noise distribution, some channels are preventing the global model to train as well as in the other case. I don't think it is a bug, just a consequence of the way it is implemented.

In which case, I would suggest you just train on the individual channels. It is a bit cumbersome, but if the results are better you should stick to that.

**Comment by honghongfang** [comment]
thank you. I have another question, structN2Vmask=None, how will blind-spots be generated? because it will not apply apply_structN2Vmask in N2V_DataWrapper file, even in the config file, structN2Vmask=None, and ok['structN2Vmask'] = True

**Comment by jdeschamps** [comment]
> thank you. I have another question, structN2Vmask=None, how will blind-spots be generated? because it will not apply apply_structN2Vmask in N2V_DataWrapper file, even in the config file, structN2Vmask=None, and ok['structN2Vmask'] = True

The blind-spot is generated for each patch in the [N2V_DataWrapper](https://github.com/juglab/n2v/blob/84f2de54c187237ef91db5e19fae30548e4ce88f/n2v/internals/N2V_DataWrapper.py#L82). The various pixel manipulators are defined [here](https://github.com/juglab/n2v/blob/main/n2v/utils/n2v_utils.py).

Then, if there is a structN2V mask, the values of the pixels around the blind spot are also "manipulated" according to the mask (see [here](https://github.com/juglab/n2v/blob/84f2de54c187237ef91db5e19fae30548e4ce88f/n2v/internals/N2V_DataWrapper.py#LL94C26-L94C45)).

**Comment by jdeschamps** [comment]
I will close this issue now.
