### ISSUE TITLE
train

### ISSUE THREAD

**Issue by tianshukai99** [juglab/n2v#141]
Hi, How can I advance my data set which is infrared images? How to start my training on server?

**Comment by jdeschamps** [comment]
Hi,

Could you explain in more details what you mean by "advance my data"?

On a server, it depends what you have access to. Here are three solutions:
- Google colab: https://github.com/HenriquesLab/ZeroCostDL4Mic
- HPC: jupyter notebooks (see [the examples](https://github.com/juglab/n2v/tree/main/examples), you will need to use port forwarding to the server) or python scripts (the scripts content will be similar to the content of the notebooks)
- Virtual machine: jupyter notebooks or python scripts (see HPC) 

If you give more details about what you have access to, we can give you some pointers.

**Comment by jdeschamps** [comment]
I will close this issue due to lack of answers, don't hesitate to open a new one if we can be of any help.
