### ISSUE TITLE
Sincere Help for Beginners

### ISSUE THREAD

**Issue by lxproot** [juglab/n2v#156]
Hello author, I don't seem to have seen any relevant model training tutorials on your homepage. I would like to ask if your project does not require users to provide dataset training, but only provides a testing denoising project?

Because I am a newcomer in the field of deep learning, my current knowledge base is very low. I have only been exposed to PyTorch framework and am not sure if there is a significant difference between it and TensorFlow. In my understanding, I need to provide my dataset and configuration related training files, then train the model, and run the test file to load the model output and obtain the results.

**Comment by jdeschamps** [comment]
Hi!

All the examples are in the [example folder](https://github.com/juglab/n2v/tree/main/examples), and provide training notebooks for various examples!

Please note that we are not actively maintaining this repo and that we are currently working on a PyTorch library to run N2V: https://careamics.github.io/0.1/.

**Comment by jdeschamps** [comment]
I'm closing this issue! Don't hesitate if you have more questions.
