### ISSUE TITLE
3D training error

### ISSUE THREAD

**Issue by RenieWell** [juglab/n2v#18]
I am try to run the notebook in `\3D\examples\01_traing.pynb.`
The code runs good in Epoch 1, but it fails in Epoch 2, and shows that

> tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [?,?,?,?,1]
	 [[{{node Placeholder}} = Placeholder[dtype=DT_FLOAT, shape=[?,?,?,?,1], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
	 [[{{node lambda_2/clip_by_value/_809}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_451_lambda_2/clip_by_value", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

It seems is a error in `n2v_standard.py` in line 216

> history = self.keras_model.fit_generator(generator=training_data, validation_data=(validation_X, validation_Y),epochs=epochs, steps_per_epoch=steps_per_epoch, callbacks=self.callbacks, verbose=1) 

Can you help me with this?
BTW, my tensorflow version is 1.12.0
keras version is 2.2.1
numpy version is 1.16.3

**Comment by tibuch** [comment]
Hi @RenieWell 

It might be that you are using an old N2V version. The current release is 0.1.4. Which version do you have installed?

**Comment by CMCI** [comment]
Hi @tibuch I am also getting the same error, having just used 
`git pull master`
to get the most up-to-date version of the code. It also occurs after having run through epoch 1, but before reaching epoch 2.

**Comment by tibuch** [comment]
Hi @RenieWell 

Unfortunately we had the wrong version numbers on our master-branch. I merged the correct version numbers and now everything should work again.

Sorry about the inconvenience and thank you for reporting the issue!

**Comment by RenieWell** [comment]
It works!
Thanks a lot!
