### ISSUE TITLE
I meet some errors when I run 02_prediction.py : UnknownError

### ISSUE THREAD

**Issue by Zhihengfeng0615** [juglab/n2v#22]
when I run this "pred_train = model.predict(input_train, axes='YX', n_tiles=(2,1))",
I have some errors:

`UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node down_level_0_no_0/convolution}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](down_level_0_no_0/convolution-0-TransposeNHWCToNCHW-LayoutOptimizer, down_level_0_no_0/kernel/read)]]
	 [[{{node activation_11/Identity/_457}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_472_activation_11/Identity", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]`

what can i do?
Thanks for your help!

**Comment by fjug** [comment]
Any other notebook running?!?
I usually encounter this when I have eg. another jupyter instance running I forgot about.
Despite drastic, a reboot should help. If it doesn’t, let us know...

**Comment by Zhihengfeng0615** [comment]
> Any other notebook running?!?
> I usually encounter this when I have eg. another jupyter instance running I forgot about.
> Despite drastic, a reboot should help. If it doesn’t, let us know...

Thanks for your help! A reboot really helps.
