### ISSUE TITLE
Input images have to be 32-bit

### ISSUE THREAD

**Issue by faymanns** [juglab/n2v#43]
The input image to `model.predict(img, axes='YX', n_tiles=(2,1))` has to be a 32-bit image.
Using 16-bit images results in hot pixels in the background with values close to the saturation value of 16-bit.

**Comment by tibuch** [comment]
Hi @faymanns 

This is true, the networks expect 32-bit float images. We should probably add a test and convert-step in our predict method.

Thanks for reporting!
