### ISSUE TITLE
Can't open LZW compressed tiff files

### ISSUE THREAD

**Issue by tibuch** [juglab/n2v#44]
tifffile does not support LZW compressed tiff files. 

We should check if Pillow can read such files and if so, we should probably use Pillow to read the images.

**Comment by turekg** [comment]
I took the train.tif file and ran it thru https://www.ps2pdf.com/compress-tiff to get an LZW compressed tif file. Then wrote a quick test to read it with tifffile and pillow. Actually it worked with tiffile but failed with pillow.

**Comment by turekg** [comment]
OK I've added a test and test file that shows that it works....

**Comment by turekg** [comment]
So, interesting.... ,my test fails on Travis but not on my machine. It turns out that if you also install Imagecodecs 2020.5.30 (see https://github.com/cgohlke/tifffile) then it works fine. For some reason I ended up with that library in my env. So if add the to setup.py it'll solve that problem.

**Comment by turekg** [comment]
Hum, no I guess tifffile did not automatically add imagecodecs. Added those to setup.py

**Comment by turekg** [comment]
OK, test passes now with setup.py updated
