### ISSUE TITLE
train and test on imagenet

### ISSUE THREAD

**Issue by cyndixxxxx** [juglab/n2v#46]
The biggest problem with training and testing the model on the Imagenet Dataset is that the resulting images lose most of their color.I see the paper is showing black-and-white images,  is there any problem about color generation in the model? Or Am I not allowed to use the IMAGENET Dataset?

**Comment by tibuch** [comment]
Hi @cyndixxxxx 

It would be great if you could provide some more information about your use-case. In particular network configuration and training time would be interesting. 

We applied Noise2Void on RGB images, see our [RGB Example](https://github.com/juglab/n2v/tree/b9121f621e5d4aa312df43ec7690f59e2e5e801d/examples/2D/denoising2D_RGB). We observe that a larger network and longer training is required compared to single channel images.

**Comment by cyndixxxxx** [comment]
We used the network configuration of your RGB example, but IMAGENET's images are . JPEG structure.

**Comment by fjug** [comment]
Hi @cyncixxxxx,

it is not easy for us to understand the issues you have without significantly more information. Could you share your code or some more details about your training setup? We would like to help you finding the issue with your data.

Did you ever just run our RGB example by itself? Did this lead to satisfying results?
If so, I guess you agree that it is possible to get to good results and we are left with finding the bug/issue/problem with the setup/code you're using.

Hope this helps,
Best,
Florian

**Comment by tibuch** [comment]
I will close this issue for now. Feel free to reopen if necessary.
