### ISSUE TITLE
About extremely slow download speed of training data

### ISSUE THREAD

**Issue by TomHeaven** [juglab/n2v#47]
Hi, thanks for your work. I'm experiencing extremely slow download speed when downloading training data at this link: https://cloud.mpi-cbg.de/index.php/s/Frru2hsjjAljpfW/download/data/RGB.zip. 

Would you please upload the training data to GoogleDrive or Dropbox? It would be great if a few pretrained model weights can be uploaded together.

**Comment by tibuch** [comment]
Hi @TomHeaven 

I tested the download form outside and had fast downloading speeds (within seconds). 

There are no plans to upload the data to Dropbox or GoogleDrive as of now. 

Providing some pre-trained models is a nice idea. We might add such a feature in the future.
