### ISSUE TITLE
5D data is not loaded correctly

### ISSUE THREAD

**Issue by oliviervenzin** [juglab/n2v#48]
Trying to load 5D data, the dimensions are interpreted wrong.
The dimensions in my tif file are ordered: TCZYX
I run:
`imgs = datagen.load_imgs_from_directory(directory = "E:/PROJECTS/Olivier/n2v images/Training", dims='TCZYX')

# Let's look at the shape of the image
print(imgs[0].shape)
` 
and get
`(5, 2, 2048, 2048, 301)`
which corresponds to TCYXZ
It should be:
TZYXC

Thanks.

**Comment by alex-krull** [comment]
Hello Oliver,
Thanks for reporting. I was however not able to reproduce this behaviour (see below).
Could it be that the order of axis in the file was not correct? Fiji, is e.g. giving a order of axis that is different from what you get when you open it with tifffile in python.
![image](https://user-images.githubusercontent.com/1193459/68377284-5ac09680-014a-11ea-96f3-f019ef0877e7.png)

**Comment by alex-krull** [comment]
I think that the way axes are handled currently is a little confusing. We are working on imporving this in the next release.
