### ISSUE TITLE
Issue with plotting

### ISSUE THREAD

**Issue by uschmidt83** [juglab/n2v#68]
examples/3D/02_prediction.ipynb:

<img width="509" alt="image" src="https://user-images.githubusercontent.com/231996/72970899-d5ec2d00-3dc8-11ea-9bed-254c86f8e593.png">

Subplot for `pred` shouldn't use percentiles from `img` for `vmin` and `vmax`.
Also doesn't work for 3-channel RGB images when `pred` is a float image with pixel values not in the range 0..1.

**Comment by tibuch** [comment]
Thank you for reporting.
