### ISSUE TITLE
N2V_DataGenerator error in 3D making patches

### ISSUE THREAD

**Issue by trasse** [juglab/n2v#70]
Dear All,

i tried to use the N2V_DataGenerator  to make patches out of this image:
(1, 30, 1024, 1024, 1)

print(imgs[0].shape)
X = datagen.generate_patches(imgs[0], shape=(15,512,512),augment = False)

However i get:
(1, 30, 1024, 1024, 1)
Generated patches: (1, 15, 512, 512, 1)

Instead of:
Generated patches: (8, 15, 512, 512, 1)

print(imgs[0].shape)
X = datagen.generate_patches(imgs[0], shape=(14,511,511),augment = False)
works as expected:
(1, 30, 1024, 1024, 1)
Generated patches: (8, 14, 511, 511, 1)

Thanks a lot & Kind regards

Tobias

**Comment by trasse** [comment]
I solved the issue and saved it as N2V_DataGenerator2.py
in trasse/n2v where I also added some options i needed for other reasons.

**Comment by tibuch** [comment]
Would you mind creating a pull request with the fix? 

Then we can potentially merge it into N2V and create a new release with the fix.

Best wishes

**Comment by trasse** [comment]
Yes sure. I just did.
Please check if my solution creates problems elsewhere.
I used N2V_DataGenerator for something else.
Therefore I gave it also a different name.
