### ISSUE TITLE
N2V for TF2 ?

### ISSUE THREAD

**Issue by JohnCraigPublic** [juglab/n2v#88]
I saw that CSBDeep can now work with TF2.  Does it mean I can use your N2V notebooks with TF2 now?  If so, can you give a hint how?   And which version of Keras should be used in this case.  Thanks!

**Comment by tibuch** [comment]
Hi @JohnCraigPublic 

We haven't tried it out yet. I would expect that it won't work out of the box. 

It is on our to-do list :slightly_smiling_face:

**Comment by JohnCraigPublic** [comment]
I've used your notebook to train your sample model.  Now that the model is trained and saved in TF1 -- how can I load it into TF2 ?  Have any hints for me?  Thanks!

**Comment by xtudbxk** [comment]
I just move the simplest UPM masksing scheme to tf2.0. The project is in [n2v-tensorflow](https://github.com/xtudbxk/n2v-tensorflow) and it achieves the comparable result on BSD68 dataset.

**Comment by joaomamede** [comment]
+1 for this.  My nvidia driver needs to be 460 that only works with cuda 11+, which in turn needs newer tensorflow.

**Comment by tibuch** [comment]
Just released v0.3.0 of N2V. With this version we move from TF1 to TF2.
