### ISSUE TITLE
Missing plt.show() in denoising2D_SEM/02_prediction.ipynb

### ISSUE THREAD

**Issue by Volko1** [juglab/n2v#89]
Not sure whether this is the right place to report a problem, but I think there are plt.show() commands missing in the example script denoising2D_SEM/02_prediction.ipynb in sections 5 and 6. 
I have very little experience with Python, but I could only get the script to show the plots when adding a plt.show() at the end of these two sections.

**Comment by tibuch** [comment]
I think this is related to the backend of `matplotlib`. If it is set to `inline` then the `plt.show()` command is not necessary in jupyter notebooks.

You can test this by running this in the first notebook cell: `%matplotlib inline`

Or you change the config of matplotlib to use `inline` by default.
