### ISSUE TITLE
16-bits-per-pixel images

### ISSUE THREAD

**Issue by JohnCraigPublic** [juglab/n2v#91]
I have single channel (grayscale) images that have 16-bits-per-pixel.  What do you think about using your technique to denoise such images?   Will it be possible for me to use your technique and retain 16-bits-per-pixel?   I don't want to smash the image down to 8-bits-per-pixel.

**Comment by JohnCraigPublic** [comment]
OK, sorry for the dumb questions - I see that pixel values are being expressed as floats, so as long as I watch the details of the image manipulations, it works naturally with 16-bit-per-pixel images.  I think its working for me.   I did have to use OpenCV to write out a 16-bit TIFF, but that's fine.  Thanks.  Closing....

**Comment by tibuch** [comment]
For training all images are converted to float-32bit images. This is necessary since most GPUs only work on float32 type.
