### ISSUE TITLE
A Simple Question on Training Data

### ISSUE THREAD

**Issue by JohnCraigPublic** [juglab/n2v#92]
In your example, you use one image for training and one image for validation.  But in a real application, to get best performance, one should train on hundreds or thousands of images, correct?

**Comment by JohnCraigPublic** [comment]
I see, looking at the size of your data for the BSD68 example, that you use not just a few images, but many -- as I expected.  So, I think it answers my question -- so closing the question...

**Comment by tibuch** [comment]
Eventually it depends on how much information one uses to train the network. If you have many small images or one gigantic image does not matter much. For training these images get split up into patches anyway. But in general you want to use as many pixels/information/images as possible to allow your network to generalize better over all possible images of your dataset.

**Comment by JohnCraigPublic** [comment]
OK, so not unlike any Deep Learning system.  Just wanted to be sure.  Thank you!
