### ISSUE TITLE
Suppress noise early or later in image processing?

### ISSUE THREAD

**Issue by JohnCraigPublic** [juglab/n2v#94]
In almost every image processing task, we are using operators to enhance contrast, perhaps to enhance edges.   What are your thoughts on this question:  should N2V be used "early in the processing" (perhaps on the original raw images) to suppress noise *before* it gets amplified by other image processing steps -- or should N2V be applied "last in the processing" to clean up noise that was (probably) enhanced by other processing algorithms?

**Comment by tibuch** [comment]
TL;DR: N2V should be the first processing step.

One of the prerequisites of Noise2Void is that the noise has zero-mean, which holds true for Gaussian or Poisson noise. The second requirement is that the noise is pixel-wise independent. As long as your processing steps do not violate any of the two requirements N2V should still work. But to be safe we would recommend to run N2V directly on the raw data coming from your imaging system. Although in some cases it makes sense to first subtract a dark-image to reduce some detector patterns.

**Comment by JohnCraigPublic** [comment]
Thank you.
